In [1]:
import numpy as np

In [12]:
def create_board(board): #creates the board
    return(np.zeros((board), dtype=int))

board = create_board((3,3)) #creates an instance of the board

def place(board, player, position): #make a move on the board
    if player == 1 or player == 2:
        if type(position) == tuple and len(position) == 2 and max(position) <= 2 and min(position) >= 0:
            if board[position] == 0:
                board[position] = player
                print(board)
            else:
                print('Error: someone already played that move')
        else:
            print('Error: position must be tuple length 2 within the board dimensions')
    else:
        print('Error: player must be an integer 1 or 2')

[[0 0 0]
 [0 1 0]
 [0 0 0]]


Now you can start playing until you run out of options. Try playing place(board, 1, (1,0))

In [29]:
def row_win(board, player): #defining winning conditions: winning in a row
    if np.any(np.all(board==player, axis=1)):
        return True
    else:
        return False
    
def col_win(board, player): #defining winning conditions: winning in a column
    if np.any(np.all(board==player, axis=0)):
        return True
    else:
        return False
    
def diag_win(board, player): #defining winning conditions: winning in a diagnonal
    if np.all(np.diag(board)==player) or np.all(np.diag(np.fliplr(board))==player):
        return True
    else:
        return False
    
def evaluate(board): #pulling all winning conditions together
    winner = 0
    for player in [1, 2]:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        print('This game is a tie')
    return winner

Now you can play until the end of a game and check who won once you have run out of options to play